
version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: travel_safe_shield
      POSTGRES_USER: tss_user
      POSTGRES_PASSWORD: tss_pass
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    depends_on:
      - postgres
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://tss_user:tss_pass@postgres:5432/travel_safe_shield
      DB_SSL: 'false'
      WS_PORT: 8081
    volumes:
      - ./backend:/app
    ports:
      - "3001:3001"
      - "8081:8081"
    restart: unless-stopped

  frontend:
    build:
      context: .
    depends_on:
      - backend
    ports:
      - "80:80"
    environment:
      VITE_API_URL: http://localhost:3001
      VITE_WS_URL: ws://localhost:8081
    restart: unless-stopped

volumes:
  pgdata:
