[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(self)"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[context.production.environment]
  VITE_API_URL = "https://api.travelsafeshield.com"
  VITE_WS_URL = "wss://ws.travelsafeshield.com"
  VITE_ENVIRONMENT = "production"

[context.preview.environment]
  VITE_API_URL = "https://staging-api.travelsafeshield.com"
  VITE_WS_URL = "wss://staging-ws.travelsafeshield.com"
  VITE_ENVIRONMENT = "staging"

[context.branch-deploy.environment]
  VITE_API_URL = "https://dev-api.travelsafeshield.com"
  VITE_WS_URL = "wss://dev-ws.travelsafeshield.com"
  VITE_ENVIRONMENT = "development"
